In [28]:
import pandas as pd
import numpy as np
df = pd.read_csv("https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv")
#question1
print(pd.__version__)

#question2
print(len(df))

#question3
print(df["fuel_type"].nunique())

#question4
missing_counts = df.isnull().sum().to_numpy()
print(missing_counts)
print(np.sum(missing_counts > 0))

#question5
asia_fuel_eff = df[df["origin"]=="Asia"]["fuel_efficiency_mpg"].to_numpy()
max_eff = np.max(asia_fuel_eff)
print(max_eff)


#question6
median = df["horsepower"].median()
most_freq = df["horsepower"].mode()[0]
df["horsepower"] = df["horsepower"].fillna(most_freq)
median_a = df["horsepower"].median()
if median_a > median:
    print("increased")
elif median_a < median:
    print("decreased")
else:
    print("no")

#question7
asia = df[df["origin"] == "Asia"]

X = asia[["vehicle_weight", "model_year"]].head(7).to_numpy()
print(X)
XTX = X.T @ X
print(XTX)
XTX_inv = np.linalg.inv(XTX)
print(XTX_inv)
y = np.array([
    1100,
    1300,
    800,
    900,
    1000,
    1100,
    1200
])

w = XTX_inv @ X.T @ y

print(w)

result = w.sum()

print(result)

3.0.6
10000
3
[  0   0   0   0   0   0   0 877   0 264   0]
2
41.2
decreased
[[4240 1996]
 [4310 1992]
 [4230 1997]
 [4420 1978]
 [3950 2007]
 [4750 2021]
 [4450 2019]]
[[131950500  60750580]
 [ 60750580  28041424]]
[[ 2.96830537e-06 -6.43071025e-06]
 [-6.43071025e-06  1.39675281e-05]]
[0.13644777 0.2327492 ]
0.36919696904925203
